# Generated by Django 3.2.12 on 2022-02-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0010_alter_iteminfo_brand'),
        ('stockin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockin.stockinbasic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='params.iteminfo')),
            ],
        ),
    ]
