# Generated by Django 3.2.12 on 2022-02-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0010_alter_iteminfo_brand'),
        ('stockin', '0002_stockindetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindetail',
            name='basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stockin.stockinbasic'),
        ),
        migrations.AlterField(
            model_name='stockindetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockin_details', to='params.iteminfo'),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='params.iteminfo')),
                ('stockin_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='stockin.stockindetail')),
            ],
        ),
    ]
