# Generated by Django 3.2.12 on 2022-03-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0008_stockbackbasic_stockbackdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='stockin_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='stockin.stockindetail'),
        ),
    ]
