# Generated by Django 3.2.12 on 2022-03-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0009_alter_barcode_stockin_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='amount_left',
        ),
        migrations.AddField(
            model_name='barcode',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinbasic',
            name='code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='stockindetail',
            name='basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='stockin.stockinbasic'),
        ),
    ]
