# Generated by Django 3.2.12 on 2022-03-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0010_auto_20220306_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='amount_init',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='stockinbasic',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
