# Generated by Django 3.2.12 on 2022-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0011_auto_20220307_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutbasic',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
