# Generated by Django 3.2.12 on 2022-03-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0012_stockoutbasic_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockoutdetail',
            name='amount',
        ),
    ]
