# Generated by Django 3.2.12 on 2022-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0014_auto_20220308_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinbasic',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
