# Generated by Django 3.2.12 on 2022-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0015_alter_stockinbasic_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbackbasic',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockoutbasic',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
