# Generated by Django 3.2.12 on 2022-04-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0016_auto_20220312_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinbasic',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
