# Generated by Django 3.2.12 on 2022-04-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0014_auto_20220420_0421'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('stockin', '0019_auto_20220420_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbackbasic',
            name='client',
        ),
        migrations.AddField(
            model_name='stockbackbasic',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stockbacks', to='params.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbackbasic',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stockbacks', to='user.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockbackbasic',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
