# Generated by Django 3.2.12 on 2022-04-22 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockin', '0020_auto_20220420_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbackbasic',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockoutbasic',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
