# Generated by Django 3.2.12 on 2022-04-22 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockin', '0021_auto_20220422_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbackbasic',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stockbacks', to='auth.user'),
            preserve_default=False,
        ),
    ]
