# Generated by Django 3.2.12 on 2022-04-22 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockin', '0022_alter_stockbackbasic_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoutbasic',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockouts_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
