# Generated by Django 3.2.12 on 2022-05-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockin', '0026_alter_stockbackbasic_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockdisableBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockdisables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockdisableDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockdisable_details', to='stockin.barcode')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stockin.stockdisablebasic')),
            ],
        ),
    ]
