# Generated by Django 3.2.12 on 2022-05-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0014_auto_20220420_0421'),
        ('stockin', '0027_stockdisablebasic_stockdisabledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='params.department'),
            preserve_default=False,
        ),
    ]
