# Generated by Django 3.2.12 on 2022-02-12 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_alter_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{3}$', '3 digits requires')]),
        ),
    ]
