# Generated by Django 3.2.12 on 2022-02-12 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{0,3}[0-9]{0,3}$')])),
                ('name', models.TextField(max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='params.itemtype')),
            ],
        ),
    ]
