# Generated by Django 3.2.12 on 2022-02-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0005_alter_itemtype_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specification', models.TextField(max_length=500)),
                ('unique_barcode', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='params.itemtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='params.unit')),
            ],
        ),
    ]
