# Generated by Django 3.2.12 on 2022-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0006_iteminfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminfo',
            name='unique_barcode',
        ),
        migrations.AddField(
            model_name='iteminfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unique_barcode',
            field=models.BooleanField(default=False),
        ),
    ]
