# Generated by Django 3.2.12 on 2022-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0008_auto_20220219_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='brand',
            field=models.TextField(default='nobrand', max_length=50),
            preserve_default=False,
        ),
    ]
