# Generated by Django 3.2.12 on 2022-02-28 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0010_alter_iteminfo_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{6}$')]),
        ),
    ]
