# Generated by Django 3.2.12 on 2022-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0011_alter_iteminfo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
