# Generated by Django 3.2.12 on 2022-03-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0011_alter_iteminfo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='params.itemtype'),
        ),
    ]
