# Generated by Django 3.2.12 on 2022-04-12 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0012_alter_itemtype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{0,3}$')]),
        ),
    ]
