# Generated by Django 3.2.12 on 2022-04-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0013_auto_20220412_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.IntegerField(unique=True)),
                ('statusName', models.TextField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unique_barcode',
        ),
    ]
