# Generated by Django 3.2.12 on 2022-08-11 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0015_auto_20220811_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTypeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='代码')),
                ('name', models.TextField(max_length=10, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '物品父类表',
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '单位表'},
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='type1',
        ),
        migrations.CreateModel(
            name='ItemTypeChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{0,3}$')], verbose_name='代码')),
                ('name', models.TextField(max_length=10, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='params.itemtypeparent', verbose_name='父类')),
            ],
            options={
                'verbose_name_plural': '物品子类表',
            },
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_type', to='params.itemtypechild'),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
